### ISSUE TITLE
Voice not works

### ISSUE THREAD

**Issue by Github-Aiko** [Reventaine/OpenAI-Telegram-Bot#1]
I have cloned the code and deployed it but voice is not working.

**Comment by Github-Aiko** [comment]
Traceback (most recent call last):
  File "C:\Users\Aiko\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 983, in process_update
    await coroutine
  File "C:\Users\Aiko\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_conversationhandler.py", line 811, in handle_update
    new_state: object = await handler.handle_update(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aiko\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 137, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./chat.py", line 43, in chat
    prompt = await speech_to_text(update, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./chat.py", line 24, in speech_to_text
    subprocess.call(['ffmpeg', '-i', 'speech.mp3',
  File "C:\Program Files\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
